# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status.proto',
  package='status',
  syntax='proto3',
  serialized_options=b'\n\027io.grpc.examples.statusB\013StatusProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cstatus.proto\x12\x06status\"2\n\tStatusReq\x12\x0e\n\x06module\x18\x01 \x01(\t\x12\x15\n\roptional_data\x18\x02 \x01(\t\"A\n\nStatusResp\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x32>\n\x06Status\x12\x34\n\tGetStatus\x12\x11.status.StatusReq\x1a\x12.status.StatusResp\"\x00\x42.\n\x17io.grpc.examples.statusB\x0bStatusProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_STATUSREQ = _descriptor.Descriptor(
  name='StatusReq',
  full_name='status.StatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='status.StatusReq.module', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optional_data', full_name='status.StatusReq.optional_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=74,
)


_STATUSRESP = _descriptor.Descriptor(
  name='StatusResp',
  full_name='status.StatusResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stdout', full_name='status.StatusResp.stdout', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='status.StatusResp.stderr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='status.StatusResp.status_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['StatusReq'] = _STATUSREQ
DESCRIPTOR.message_types_by_name['StatusResp'] = _STATUSRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusReq = _reflection.GeneratedProtocolMessageType('StatusReq', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQ,
  '__module__' : 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.StatusReq)
  })
_sym_db.RegisterMessage(StatusReq)

StatusResp = _reflection.GeneratedProtocolMessageType('StatusResp', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESP,
  '__module__' : 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.StatusResp)
  })
_sym_db.RegisterMessage(StatusResp)


DESCRIPTOR._options = None

_STATUS = _descriptor.ServiceDescriptor(
  name='Status',
  full_name='status.Status',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=143,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='status.Status.GetStatus',
    index=0,
    containing_service=None,
    input_type=_STATUSREQ,
    output_type=_STATUSRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATUS)

DESCRIPTOR.services_by_name['Status'] = _STATUS

# @@protoc_insertion_point(module_scope)
